# Generated by Django 4.1.13 on 2024-02-05 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_customuser_user_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationUploadDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='certification_documents/')),
                ('status', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certification_upload_documents',
            },
        ),
        migrations.CreateModel(
            name='UploadDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='documents/')),
                ('status', models.CharField(max_length=10, null=True)),
                ('member_type', models.CharField(help_text='0=>all, 1=>individual, 2=>organizational , 3=>accredited ', max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_documents',
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='images/')),
                ('status', models.CharField(max_length=10, null=True)),
                ('member_type', models.CharField(help_text='0=>all, 1=>individual, 2=>organizational , 3=>accredited ', max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_image',
            },
        ),
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='videos/')),
                ('status', models.CharField(max_length=10, null=True)),
                ('member_type', models.CharField(help_text='0=>all, 1=>individual, 2=>organizational , 3=>accredited ', max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_videos',
            },
        ),
        migrations.CreateModel(
            name='UploadVideoMembershipMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uvmm_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.ommembershipplan')),
                ('uvmm_video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.uploadvideo')),
            ],
            options={
                'db_table': 'upload_video_membership_mapping',
            },
        ),
        migrations.CreateModel(
            name='UploadImageMembershipMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uimm_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.uploadimage')),
                ('uimm_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.ommembershipplan')),
            ],
            options={
                'db_table': 'upload_image_membership_mapping',
            },
        ),
        migrations.CreateModel(
            name='UploadDocumentsMembershipMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udmm_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.uploaddocuments')),
                ('udmm_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.ommembershipplan')),
            ],
            options={
                'db_table': 'upload_documents_membership_mapping',
            },
        ),
        migrations.CreateModel(
            name='CertificationUploadDocumentsMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerdoc_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.certificationuploaddocuments')),
                ('cerdoc_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certification_upload_doc_mapping',
            },
        ),
    ]
