# Generated by Django 2.2.2 on 2021-10-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationUploadDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='certification_documents/')),
                ('status', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'certification_upload_documents',
            },
        ),
        migrations.CreateModel(
            name='CertificationUploadDocumentsMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'certification_upload_doc_mapping',
            },
        ),
        migrations.CreateModel(
            name='UploadDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='documents/')),
                ('status', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'upload_documents',
            },
        ),
        migrations.CreateModel(
            name='UploadDocumentsMembershipMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'upload_documents_membership_mapping',
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='images/')),
                ('status', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'upload_image',
            },
        ),
        migrations.CreateModel(
            name='UploadImageMembershipMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'upload_image_membership_mapping',
            },
        ),
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='videos/')),
                ('status', models.CharField(max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'upload_videos',
            },
        ),
        migrations.CreateModel(
            name='UploadVideoMembershipMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'upload_video_membership_mapping',
            },
        ),
    ]
