# Generated by Django 4.1.13 on 2024-02-02 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_certificate_customuser_created_by_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationuploaddocuments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificationuploaddocumentsmapping',
            name='cerdoc_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.certificationuploaddocuments'),
        ),
        migrations.AddField(
            model_name='certificationuploaddocumentsmapping',
            name='cerdoc_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploaddocuments',
            name='member_type',
            field=models.CharField(help_text='0=>all, 1=>individual, 2=>organizational , 3=>accredited ', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploaddocuments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploaddocumentsmembershipmapping',
            name='udmm_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.uploaddocuments'),
        ),
        migrations.AddField(
            model_name='uploaddocumentsmembershipmapping',
            name='udmm_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.ommembershipplan'),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='member_type',
            field=models.CharField(help_text='0=>all, 1=>individual, 2=>organizational , 3=>accredited ', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadimagemembershipmapping',
            name='uimm_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.uploadimage'),
        ),
        migrations.AddField(
            model_name='uploadimagemembershipmapping',
            name='uimm_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.ommembershipplan'),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='member_type',
            field=models.CharField(help_text='0=>all, 1=>individual, 2=>organizational , 3=>accredited ', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadvideomembershipmapping',
            name='uvmm_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.ommembershipplan'),
        ),
        migrations.AddField(
            model_name='uploadvideomembershipmapping',
            name='uvmm_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.uploadvideo'),
        ),
    ]
