# Generated by Django 4.1.13 on 2024-02-05 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_customuser_user_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(null=True, upload_to='certification_documents/')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.ommembershipplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_certificate',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(help_text='Payment transaction id', max_length=200, null=True)),
                ('order_id', models.CharField(help_text='Payment order id', max_length=200, null=True)),
                ('user_email', models.CharField(max_length=200, null=True)),
                ('customer_ref', models.CharField(help_text='payment customer reference', max_length=200, null=True)),
                ('currency', models.CharField(max_length=200, null=True)),
                ('payment_status', models.CharField(help_text='success, failed', max_length=200, null=True)),
                ('payment_mode', models.CharField(max_length=100, null=True)),
                ('payment_for', models.CharField(default='buy subscription', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=20, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.ommembershipplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
