# Generated by Django 2.2.2 on 2021-10-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.CharField(help_text='Payment transaction id', max_length=200, null=True)),
                ('order_id', models.CharField(help_text='Payment order id', max_length=200, null=True)),
                ('user_email', models.CharField(max_length=200, null=True)),
                ('customer_ref', models.CharField(help_text='payment customer reference', max_length=200, null=True)),
                ('currency', models.CharField(max_length=200, null=True)),
                ('payment_status', models.CharField(help_text='success, failed', max_length=200, null=True)),
                ('payment_mode', models.CharField(max_length=100, null=True)),
                ('payment_for', models.CharField(default='buy subscription', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=20, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
