# Generated by Django 4.1.13 on 2024-02-02 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_customuser_certificate_customuser_created_by_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_ceo_name', models.CharField(max_length=100, null=True)),
                ('facility_ceo_phone', models.BigIntegerField(null=True)),
                ('facility_ceo_email', models.CharField(max_length=100, null=True)),
                ('medical_director_name', models.CharField(max_length=100, null=True)),
                ('medical_director_phone', models.BigIntegerField(null=True)),
                ('medical_director_email', models.CharField(max_length=100, null=True)),
                ('cnt_aaqf_name', models.CharField(max_length=100, null=True)),
                ('cnt_aaqf_phone', models.BigIntegerField(null=True)),
                ('cnt_aaqf_email', models.CharField(max_length=100, null=True)),
                ('acnt_name', models.CharField(max_length=100, null=True)),
                ('acnt_phone', models.BigIntegerField(null=True)),
                ('acnt_email', models.CharField(max_length=100, null=True)),
                ('web_facility_type', models.CharField(help_text='Facility Website', max_length=100, null=True)),
                ('providers', models.CharField(help_text='Service Providers', max_length=100, null=True)),
                ('tax_identification_no', models.CharField(max_length=100, null=True)),
                ('others', models.CharField(max_length=100, null=True)),
                ('survey_dt', models.DateTimeField(auto_now_add=True)),
                ('save_as', models.CharField(default='2', help_text='1=>submit, 2=>draft', max_length=100, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.BooleanField(default=False)),
                ('accreditation', models.ForeignKey(help_text='accreditation plans', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ommembershipplan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserInfoMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trf_owner_name', models.CharField(help_text='Transfer Business Owner Name', max_length=200, null=True)),
                ('trf_personal_address', models.CharField(help_text='Transfer Personal Address', max_length=200, null=True)),
                ('trf_phone', models.BigIntegerField(help_text='Transfer Phone', null=True)),
                ('trf_email', models.CharField(help_text='Transfer Phone', max_length=100, null=True)),
                ('user_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.userinfo')),
            ],
            options={
                'db_table': 'user_info_mapping',
            },
        ),
    ]
