"""
Django settings for aaqf project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8@q54^go8ks^3yj*y0i3j^3%v+_7)ll5)=#)0*ic^lsmb_oyx9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    'add_paper',
    'payment',
    'resource',
    'accounts'
]

AUTH_USER_MODEL = 'user.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aaqf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user.context_processors.get_user_role', # getting user role
                'user.context_processors.membership_details', # getting membership_details
            ],
        },
    },
]

WSGI_APPLICATION = 'aaqf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'aaqf1',
#         'USER': 'postgres',
#         'HOST': 'localhost',
#         'PASSWORD': 'qwerty',
#         'PORT': '5432',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'aaqf1',
#         'USER': 'paymaster_user',
#         'HOST': 'uat-db-1.ca3aobht1eln.ap-south-1.rds.amazonaws.com',
#         'PASSWORD': '217dg8ev7wbi',
#         'PORT': '5432',
#     }
# }
# DATABASES = {}
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'omdb',
#         'ENFORCE_SCHEMA': False,
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# STATIC_URL = '/static/'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
LOGIN_REDIRECT_URL = '/home'
LOGOUT_REDIRECT_URL = '/user/login/'
LOGIN_URL = '/user/login/'

EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = 'aaqfteam@gmail.com'
SERVER_EMAIL = 'imap.gmail.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'aaqfteam@gmail.com'
EMAIL_HOST_PASSWORD = 'Harry@biotech!'

# DEFAULT_FROM_EMAIL = 'info@aaqf.net'
# SERVER_EMAIL = 'mail.aaqf.net'
# EMAIL_HOST = 'mail.aaqf.net'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'info@aaqf.net'
# EMAIL_HOST_PASSWORD = 'E+8)J_U#vrQh'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# settings.py
# STRIPE_SECRET_KEY = 'sk_test_51JLXTsSB24BFGIlRfpCyECdkMgzHCaS6UFMWxlP7VjVazCvUCorGaqltYI3aGajSBOZjDdvAhnB72MWHhpqlIGMj002KTCbdpX'
STRIPE_SECRET_KEY = 'sk_test_51HUJ0ZGYzveC7pksHEjRKaY9pWaGNHIKkZ2u01Tm0TJi0KTGFjyYBooMSRl9JuU9Zs3Wuw0X4f7rQ7YcCQIwgy1D00tKTjSlIP'
# STRIPE_PUBLISHABLE_KEY = 'pk_test_51JLXTsSB24BFGIlRd7fGnfoplkmoPMNykITd8yIhZajX5tlqi3h8zJU5xfhRJpVv3ns9jmn4dEBy8NFlUwlybhaa00rQ6iaOqT'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51HUJ0ZGYzveC7pksbowlNuRXlbFCt4qsLlvY0ZckpX5pUqqN9AzZEDthj4zqhYVjlk87GGVwsnyo7rO63t5rG7Ju00MAQ5qDqp'
