# Generated by Django 4.1.13 on 2024-02-05 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperList',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_title', models.TextField(null=True)),
                ('paper_desc', models.TextField(null=True)),
                ('paper_file', models.FileField(blank=True, null=True, upload_to='paper')),
                ('paper_cr_dt', models.DateTimeField(auto_now=True, null=True)),
                ('paper_upd_dt', models.DateTimeField(null=True)),
                ('paper_marks', models.IntegerField(default=0)),
                ('paper_rank', models.IntegerField(default=0)),
                ('paper_submit_tf', models.BooleanField(default=False, null=True)),
                ('paper_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paper_list',
            },
        ),
        migrations.CreateModel(
            name='VerifiedPaper',
            fields=[
                ('vp_id', models.AutoField(primary_key=True, serialize=False)),
                ('vp_cr_dt', models.DateTimeField(auto_now=True)),
                ('vp_upd_dt', models.DateTimeField(null=True)),
                ('vp_paper1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vp_paper1', to='add_paper.paperlist')),
                ('vp_paper2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vp_paper2', to='add_paper.paperlist')),
                ('vp_selected_paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vp_selected_paper', to='add_paper.paperlist')),
                ('vp_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verified_paper',
            },
        ),
    ]
