# Generated by Django 4.1.13 on 2024-02-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_op',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.omprefix'),
        ),
    ]
